[start]
command:/usr/local/etc/rc.d/nclink onestart
parameters:
type:script_output
message:starting NC-Link service

[stop]
command:/usr/local/etc/rc.d/nclink stop
parameters:
type:script_output
message:stopping NC-Link service

[restart]
command:/usr/local/etc/rc.d/nclink onerestart
parameters:
type:script_output
message:restarting NC-Link service

[status]
command:/usr/local/etc/rc.d/nclink status
parameters:
type:script_output
message:getting NC-Link service status
