PLUGIN_NAME=        nclink
PLUGIN_VERSION=     0.1.0
PLUGIN_COMMENT=     NC-Link 智能工厂数控机床互联接口协议栈
PLUGIN_MAINTAINER=  yourname@example.com
PLUGIN_WWW=         https://github.com/yxlee3714/plugins/tree/master/net-mgmt/os-nclink

PLUGIN_DEPENDS=     python311 py311-pip py311-loguru py311-pydantic

.include "../../Mk/plugins.mk:"
