PLUGIN_NAME=        os-nclink
PLUGIN_VERSION=     1.0.0
PLUGIN_COMMENT=     NC-Link Agent - 智能工厂数控机床互联接口（国标）
PLUGIN_MAINTAINER=  Your Name <your@email.com>
PLUGIN_VERSIONS=    24.7 25.1
PLUGIN_REVISION=    0

.include "../../Mk/plugins.mk"